### ISSUE TITLE
Wrong number of parameters in `mysql_connect' method. Got 4 expect 3

### ISSUE THREAD

**Issue by ingmarioalberto** [jcubic/jsh.php#4]
Hello, 
mysql -u USER -h 127.0.0.1 DATABASE
Wrong number of parameters in `mysql_connect' method. Got 4 expect 3

Method is receiving all 4 parameters, but $host="127.0.0.1" is optional,  and getNumberOfRequiredParameters is reporting that only needs 3. 
So, maybe you need to modify this line:
if ($num_got != $num_expect) 
with something else...

**Comment by jcubic** [comment]
Thanks for the repo, the issue is fixed.

**Comment by pulketo** [comment]
Thank you, my friend, for your time, this is the most useful software, for a PHP Developer and a Sysadmin without access to a real shell.
